export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};
export default function About() {
    // throw new Error("there is a problem with this page");
    
    return (
      <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
        <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
          <h2 className="text-start">hello my sweet about</h2>
        </main>
      </div>
    );
  }
  